export type Product = {
  id: string;
  slug: string;
  name: string;
  category: string;
  subcategory: string;
  price: number;
  oldPrice?: number;
  rating: number;
  reviews: number;
  thumbnail_image?: string;
  thumbnail_alt?: string | null;
  image?: string;
  images?: { id: number; image: string }[];
  unit: string;
  description: string;
  stock: number;
  is_featured?: boolean;
  is_best_seller?: boolean;
  meta_title?: string | null;
  meta_description?: string | null;
};
